things= []
famous_person=(input("Give me a famous person."))
things.append(famous_person)

delicacy=input("Give me a food")
things.append(delicacy)
noun=input("Give me a noun")
things.append(noun)
adverb=input("Give me a adverb")
things.append(adverb)
novel=input("give me a novel")
things.append(novel)
famous_car=(input("Give me a famous car"))
things.append(famous_car)
resturant=(input("give me a resturant"))
things.append(resturant)
clothes_store=(input("Give me a clothes store"))
things.append(clothes_store)
another_famous_person=(input("Give me another famous person"))
things.append(another_famous_person)
famous_place=(input("give me a famous place"))
things.append(famous_place)
print(f"{things[0]} ate {things[1]}and {things[3]}read {things[4]} Then when {things[2]} snored,{things[1]} jumped into a {things[5]} and drove to {things[6]} and {things[7]}Then, in {things[5]}he/she went to his wedding with {things[8]} at {things[9]}")